name: check open appointment for foreign licence
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "5 */2 * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5